name: CI

on:
  push:
    branches: [ "main", "master", "feat/*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.2.8'
        stack-version: '2.11.1'

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-

    - name: Install dependencies
      run: stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

    - name: Build
      run: stack build --test --bench --no-run-tests --no-run-benchmarks

    - name: Run tests
      run: stack test

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests

    - name: Run Integration Tests
      run: |
        # Start the server in the background
        stack exec kamyu-exe &
        SERVER_PID=$!
        
        # Run tests
        pytest test/integration_test.py
        
        # Kill the server
        kill $SERVER_PID

  lint:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up HLint
      uses: haskell-actions/hlint-setup@v2

    - name: Run HLint
      uses: haskell-actions/hlint-run@v2
      with:
        path: '["src/", "app/", "test/"]'
        fail-on: warning

    - name: Setup Haskell (for Ormolu)
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.2.8'
        stack-version: '2.11.1'

    - name: Install Ormolu
      run: stack install ormolu

    - name: Check Formatting
      run: |
        export PATH=$HOME/.local/bin:$PATH
        ormolu -i src/Web/Kamyu/*.hs

